server:
  servlet:
    context-path: /api
    session:
      timeout: 30m
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/random?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: random
    password: random
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000 # 连接超时时间（毫秒）
    # 下面可以不加，加的话必须引入commons-pool2的依赖
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: top.plgxs.entity
  global-config:
    db-config:
      #主键类型
      #AUTO 数据库ID自增
      #INPUT 用户输入ID
      #ID_WORKER 全局唯一ID，Long类型的主键
      #ID_WORKER_STR 字符串全局唯一ID
      #UUID 全局唯一ID，UUID类型的主键
      #NONE 该类型为未设置主键类型
      id-type: ID_WORKER_STR
      #逻辑删除配置
      logic-delete-value: 1  #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  #逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

# 自定义redis key
redis:
  prefix: 'random'
  key:
    resourceList: 'menu:resourceList'
  expire:
    common: 86400 # 超期时间24h


jwt:
  # JWT存储的请求头
  header: Authorization
  # JWT加解密使用的密钥(Base64编码)
  secret: Stranger
  # JWT令牌过期时间 此处单位/秒 (60*60*24*1)(1天)
  expiration: 86400
  # JWT令牌前缀
  tokenHead: 'Bearer '

secure:
  ignored:
    # 安全路径白名单
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.css
      - /**/*.js
      - /**/*.ico
      - /**/*.png
      - /**/*.jpg
      - /login
      - /register
      - /info
      - /logout

# 日志
logging:
  level:
    root: warn
    top.plgxs.mbg.mapper: trace
  pattern:
    console: '%p%m%n'