# 项目相关配置
aster:
  # 名称
  name: Aster
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/aster/uploadPath，Linux配置 /home/aster/uploadPath）
  profile: D:/aster/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 是否允许注册
  isRegister: true

server:
  servlet:
    context-path: /
    session:
      timeout: 30m
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/random?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: random
    password: random
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  thymeleaf:
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    #mode: HTML5
    #编码 可不用配置
    #encoding: UTF-8
    #内容类别,可不用配置
    #content-type: text/html
    #配置模板路径，默认是templates，可以不用配置
    #prefix: classpath:/templates
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000 # 连接超时时间（毫秒）
    # 下面可以不加，加的话必须引入commons-pool2的依赖
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: top.plgxs.entity
  global-config:
    db-config:
      #主键类型
      #AUTO 数据库ID自增
      #INPUT 用户输入ID
      #ID_WORKER 全局唯一ID，Long类型的主键
      #ID_WORKER_STR 字符串全局唯一ID
      #UUID 全局唯一ID，UUID类型的主键
      #NONE 该类型为未设置主键类型
      id-type: ID_WORKER_STR
      #逻辑删除配置
      logic-delete-value: 1  #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  #逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
    # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）KeyGenerator keygen = KeyGenerator.getInstance("AES"); SecretKey deskey = keygen.generateKey(); System.out.println(Base64.encodeToString(deskey.getEncoded()));
    cipherKey: xoS/YbQ5cGKeorVP2nrPmA==
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 自定义redis key
redis:
  prefix: 'random'
  key:
    resourceList: 'menu:resourceList'
  expire:
    common: 86400 # 超期时间24h

jwt:
  # JWT存储的请求头
  header: Authorization
  # JWT加解密使用的密钥(Base64编码)
  secret: Stranger
  # JWT令牌过期时间 此处单位/秒 (60*60*24*1)(1天)
  expiration: 86400
  # JWT令牌前缀
  tokenHead: 'Bearer '

secure:
  ignored:
    # 安全路径白名单
    urls:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /api/**
      - /css/**
      - /images/**
      - /js/**
      - /lib/**
      - /page/**
      - /login
      - /register
      - /info
      - /logout
      - /index

# 日志
logging:
  level:
    root: warn
    top.plgxs.mbg.mapper: trace
  pattern:
    console: '%p%m%n'