spring:
  # 动态数据源配置
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        loginUsername: aster
        loginPassword: aster12138
    dynamic:
      druid: # 以下是全局默认值，可以全局更改
        # 监控统计拦截的filters
        filters: stat,wall
        initial-size: 5 # 初始化时建立物理连接的个数
        min-idle: 5 # 最小连接池数量
        max-active: 20 # 最大连接池数量
        max-wait: 60000 # 获取连接等待超时时间,单位毫秒
        time-between-eviction-runs-millis: 60000 # 间隔多久进行一次检测，检测需要关闭的空闲连接
        min-evictable-idle-time-millis: 300000 # 连接的最小生存时间.连接保持空闲而不被驱逐的最小时间
        validation-query: SELECT 'x'
        test-while-idle: true # 申请连接时检测空闲时间，根据空闲时间再检测连接是否有效.建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRun
        test-on-borrow: false # 申请连接时直接检测连接是否有效.申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: false # 归还连接时检测连接是否有效.归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        pool-prepared-statements: false # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        max-pool-prepared-statement-per-connection-size: 20 # 设置PSCache值
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          multi-statement-allow: true
      primary: master # 设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/aster?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
          username: aster
          password: aster12138
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_0:
          url: jdbc:mysql://localhost:3306/aster?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
          username: aster
          password: aster12138
          driver-class-name: com.mysql.cj.jdbc.Driver

  # 分表配置
  shardingsphere:
    # 打开sql控制台输出日志
    props:
      sql:
        show: true
    datasource:
      # 数据源名称,多个以逗号分隔,名称不能重复
      names: shardingmaster
      shardingmaster:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/aster?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: aster
        password: aster12138
    sharding:
      tables:
        c_child_info:
          # 分表策略, 分表：2, 真实表名：c_child_info_0
          actualDataNodes: shardingmaster.c_child_info_$->{0..1}
          # 分库策略
          databaseStrategy:
            none:
          tableStrategy:
            inline:
              # 分片列名称
              shardingColumn: child_id
              # 分片算法行表达式
              algorithmExpression: c_child_info_$->{(child_id.hashCode() & Integer.MAX_VALUE) % 2}
          # 主键策略 雪花算法
          keyGenerator:
            type: SNOWFLAKE
            column: child_id


