server:
  servlet:
    context-path: /random
    session:
      timeout: 30m
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/random?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: random
    password: random
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  thymeleaf:
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    #mode: HTML5
    #编码 可不用配置
    #encoding: UTF-8
    #内容类别,可不用配置
    #content-type: text/html
    #配置模板路径，默认是templates，可以不用配置
    #prefix: classpath:/templates
#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: top.plgxs.entity
  global-config:
    db-config:
      #主键类型
      #AUTO 数据库ID自增
      #INPUT 用户输入ID
      #ID_WORKER 全局唯一ID，Long类型的主键
      #ID_WORKER_STR 字符串全局唯一ID
      #UUID 全局唯一ID，UUID类型的主键
      #NONE 该类型为未设置主键类型
      id-type: ID_WORKER_STR
      #逻辑删除配置
      logic-delete-value: 1  #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0  #逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

# 日志
logging:
  level:
    root: warn
    top.plgxs.mbg.mapper: trace
  pattern:
    console: '%p%m%n'